name: pr-times-hackathon
services:
  fe:
    build:
      context: .
    command: sh -c "yarn install && yarn dev"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    tty: true
